Add 1.20.6 support (paper only)
ds58/Panilla pull request #150
Opened 2024-08-05 14:41 UTC by tangjin0418

- Using NBT-API for componential NBT adapting.
- Migrated old format checks (ignore checks that just return PASS).

Plugin Commission by @TWME-TW.

2024-08-05 15:09 UTC, ds58 commented
Thanks. I will be looking at this very soon.

2024-08-05 16:14 UTC, tangjin0418 commented
I have added some fixes.
The 1.20.5 is a significant data structure update, so there are lots of difference in NBT.
I have tried my best in migrating them to new format.
If there's any flaw, don't hesitate to let me know!

2024-08-05 22:34 UTC, Nielsbest commented
Is there a jar file of the 1.20.6 version for Panilla already? Kinda have an issue with people abusing these nbt items.

2024-08-05 23:43 UTC, ds58 requested changes

2024-08-05 23:43 UTC, ds58 commented on paper-v1_20_6/paper-1.20.6.jar
Can we depend on Spigot via local maven artifact? Is there anything specific to Paper in this PR?

In any case, please remove the .jar from the repo.

2024-08-05 23:43 UTC, ds58 commented on paper-v1_20_6/src/main/java/com/ruinscraft/panilla/paper/v1_20_6/io/PacketInspector.java
> +import de.tr7zw.changeme.nbtapi.NBTItem;
Unused import

2024-08-05 23:43 UTC, ds58 commented on paper-v1_20_6/src/main/java/com/ruinscraft/panilla/paper/v1_20_6/nbt/NbtTagCompound.java
> +import com.ruinscraft.panilla.api.nbt.INbtTagCompound;
Unused import

2024-08-05 23:43 UTC, ds58 commented on api/src/main/java/com/ruinscraft/panilla/api/nbt/checks/NbtCheck.java
What happened with this file?

2024-08-05 23:43 UTC, ds58 commented on api/src/main/java/com/ruinscraft/panilla/api/nbt/checks/NbtCheck_BlockEntityTag.java
> +        if (item.hasKey("tags")) {
I believe this change will break previous versions of Minecraft, no?

2024-08-05 23:43 UTC, ds58 commented on bukkit/src/main/java/com/ruinscraft/panilla/bukkit/JoinQuitListener.java
> +//        panilla.getInventoryCleaner().clean(pplayer);
Was there a reason you disabled this?

2024-08-05 23:47 UTC, tangjin0418 commented on paper-v1_20_6/paper-1.20.6.jar
Paper removed craftbukkit relocation in 1.20.5, that's why it's different w/ spigot now.
You can change this to import paper server instead of a jar.

https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

2024-08-05 23:48 UTC, tangjin0418 commented on api/src/main/java/com/ruinscraft/panilla/api/nbt/checks/NbtCheck_BlockEntityTag.java
> +        if (item.hasKey("tags")) {
Ah, just made a mistake.
I exceptionally changed that to "components" before, then back to "tags" but didn't realize that there is no s suffix.

2024-08-05 23:50 UTC, tangjin0418 commented on bukkit/src/main/java/com/ruinscraft/panilla/bukkit/JoinQuitListener.java
> +//        panilla.getInventoryCleaner().clean(pplayer);
Debug fault, forget to add back.
I'll clean up all these problems.

2024-08-05 23:56 UTC, ds58 commented on paper-v1_20_6/paper-1.20.6.jar
Yes, can you change it to import a maven artifact from a maven server repo or the local maven repo?

I really don't like those sketchy online repos that host paper jars, but I will add an exception to get this done.

2024-08-06 00:01 UTC, tangjin0418 commented on api/src/main/java/com/ruinscraft/panilla/api/nbt/checks/NbtCheck.java
It seems that my IDE is doing smth stupid, will try get rid of this file.

2024-08-06 08:24 UTC, tangjin0418 commented on paper-v1_20_6/paper-1.20.6.jar
I couldn't find any online repo that provides paper jar.
It appears that we have to use paperweight plugin, but I didn't find a way to let it work correctly.
Maybe, can you look into it?

2024-08-07 06:44 UTC, tangjin0418 commented on paper-v1_20_6/paper-1.20.6.jar
codemc nms repo doesn't actually contain paper-server.
`BuildTools` is for building spigot, for paper we need use `paperweight`, but I can't really make that work on a submodule-project like this.

2024-08-07 21:36 UTC, ds58 commented on paper-v1_20_6/paper-1.20.6.jar
Okay, we should find some other solution. Is it possible to build paper and then install it locally to your local maven repo?

2024-08-08 19:21 UTC, tangjin0418 commented on paper-v1_20_6/paper-1.20.6.jar
Done.

2024-08-09 00:19 UTC, ds58 commented
I did some testing. Looks like we'll have to change the way enchantments are checked. They are no longer stored as a list. `minecraft:enchantments` has a compound tag called `levels` which has each enchantment stored as a named integer.

Would you be capable of making the change to support this? I would create an enchantments NbtCheck in your new paper1_20_6 package and remove the `minecraft:enchantments` and `minecraft:stored_enchantments` from `NbtCheck_ench`.

I am suspicious that other things may have changed too. I wish I had added some sort of unit testing to this project.

2024-08-09 02:26 UTC, tangjin0418 commented
Sure, please help me find out other checks that I missed.
I will work on the enchantment check in 2 days.

2024-08-11 11:59 UTC, tangjin0418 commented
Enchantment fix done.

2024-08-12 16:28 UTC, ds58 commented
> Enchantment fix done.

Thanks. I'll check it today.

2024-08-12 23:14 UTC, ds58 commented
Looks great. I am going to go ahead and merge this, do some formatting cleanup, and make a release.

Thank you again for your contributions!

2024-08-12 23:14 UTC, merged